services:
  payment-processor-subscription:
    image: ghcr.io/reitansora/payment-processor-subscription:latest
    container_name: payment-processor-subscription
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - payment-processor-subscription
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
